### ISSUE TITLE
get_neg_v_neg_sampling implementation

### ISSUE THREAD

**Issue by zluo01** [Adoni/word2vec_pytorch#7]
``` 
def get_neg_v_neg_sampling(self, pos_word_pair, count):
        neg_v = numpy.random.choice(
            self.sample_table, size=(len(pos_word_pair), count)).tolist()
        return neg_v
```
Just wonder does negative sampling need to avoid sampling the word  from the pos_v ?

Thank you

**Comment by zyxdSTU** [comment]
你仔细看的话，会发现作者负采样的是伪附近词，而不是伪中心词。作者并没有考虑重复的问题
代码如下：
 neg_emb_v = self.v_embeddings(neg_v)
#与真的中心词进行计算损失，表明其实伪附近词
 neg_score = torch.bmm(neg_emb_v, emb_u.unsqueeze(2)).squeeze()
